apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 3000     # Service port
    targetPort: 3000  # Pod's containerPort
  type: ClusterIP

