apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 80       # Service port
    targetPort: 80  # Pod's containerPort
  type: ClusterIP

